[package]
name = "gosyn"
version = "0.1.0"
edition = "2021"
authors = ["Kevin Chen <kevin@chenbc.me>"]
description = "Golang syntax parser in Rust"
repository = "https://github.com/chikaku/gosyn"
documentation = "https://docs.rs/gosyn"
readme = "README.md"
license = "MIT"

[dependencies]
unic-ucd-category = "0.9.0"
roset = { git = "https://github.com/chikaku/roset", version = "0.1.0" }

[dev-dependencies]
pprof = { version = "0.6.2", features = ["flamegraph", "protobuf"] }
